import Head from "next/head";
import Image from "next/image";
import { async } from "regenerator-runtime";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const defaultEndPoint = `https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  }`;
  const res = await fetch(defaultEndPoint);
  const data = await res.json();
  // console.log(data);
  return {
    props: {
      data,
    },
  };
}

//client rendering
export default function Home({ data }) {
  // console.log(data);
  return (
    <div>
      <Head>
        <title>Arash &mdash; Movies</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Nav />
      <Results data={data} />
    </div>
  );
}

// server side rendering
// export async function getServerSideProps(context) {
//   const genre = context.query.genre;
//   console.log("ehllo");
//   //url that the user came in with
//   const request = await fetch(
//     `https://api.themoviedb.org/3${
//       requests[genre]?.url || requests.fetchTrending.url
//     }`
//   ).then((res) => res.json);
//   return {
//     props: {
//       // results: request.results,
//     },
//   };
// }
